"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from typing import Any

from django.db.models import Model
from django.db.models.options import Options
from django.http import HttpRequest

from wagtail_modeladmin.helpers.permission import PermissionHelper
from wagtail_modeladmin.helpers.url import AdminURLHelper

class ButtonHelper:
    default_button_classnames = ...
    add_button_classnames = ...
    inspect_button_classnames = ...
    edit_button_classnames: Sequence[str] = ...
    delete_button_classnames = ...
    verbose_name: str
    verbose_name_plural: str
    model: type[Model]
    request: HttpRequest
    opts: Options[Any]
    url_helper: AdminURLHelper
    permission_helper: PermissionHelper[Any]

    def __init__(self, view, request) -> None:
        ...

    def finalise_classname(self, classnames_add=..., classnames_exclude=...): # -> str:
        ...

    def add_button(self, classnames_add=..., classnames_exclude=...): # -> dict[str, Any | str]:
        ...

    def inspect_button(self, pk, classnames_add=..., classnames_exclude=...): # -> dict[str, Any | str]:
        ...

    def edit_button(self, pk, classnames_add=..., classnames_exclude=...): # -> dict[str, Any | str]:
        ...

    def delete_button(self, pk, classnames_add=..., classnames_exclude=...): # -> dict[str, Any | str]:
        ...

    def get_buttons_for_obj(self, obj, exclude=..., classnames_add=..., classnames_exclude=...): # -> list[Any]:
        ...

    def get_primary_button(self, obj): # -> dict[str, Any | str] | None:
        ...



class PageButtonHelper(ButtonHelper):
    unpublish_button_classnames = ...
    copy_button_classnames = ...
    def unpublish_button(self, pk, classnames_add=..., classnames_exclude=...): # -> dict[str, Any | str]:
        ...

    def copy_button(self, pk, classnames_add=..., classnames_exclude=...): # -> dict[str, Any | str]:
        ...

    def get_buttons_for_obj(self, obj, exclude=..., classnames_add=..., classnames_exclude=...): # -> list[Any]:
        ...



