"""
This type stub file was generated by pyright.
"""

class BaseSearchHandler:
    def __init__(self, search_fields) -> None:
        ...
    
    def search_queryset(self, queryset, search_term, **kwargs):
        """
        Returns an iterable of objects from ``queryset`` matching the
        provided ``search_term``.
        """
        ...
    
    @property
    def show_search_form(self): # -> Literal[True]:
        """
        Returns a boolean that determines whether a search form should be
        displayed in the IndexView UI.
        """
        ...
    


class DjangoORMSearchHandler(BaseSearchHandler):
    def search_queryset(self, queryset, search_term, **kwargs):
        ...
    
    @property
    def show_search_form(self): # -> bool:
        ...
    


class WagtailBackendSearchHandler(BaseSearchHandler):
    default_search_backend = ...
    def search_queryset(self, queryset, search_term, preserve_order=..., operator=..., backend=..., **kwargs): # -> Any:
        ...
    


