"""
This type stub file was generated by pyright.
"""

from django.utils.functional import cached_property

class AdminURLHelper:
    def __init__(self, model, base_url_path=...) -> None:
        ...
    
    def get_action_url_pattern(self, action): # -> str:
        ...
    
    def get_action_url_name(self, action): # -> str:
        ...
    
    def get_action_url(self, action, *args, **kwargs): # -> str:
        ...
    
    @cached_property
    def index_url(self): # -> str:
        ...
    
    @cached_property
    def create_url(self): # -> str:
        ...
    


class ModelAdminURLFinder:
    def __init__(self, user) -> None:
        ...
    
    def get_edit_url(self, instance): # -> None:
        ...
    


class PageAdminURLHelper(AdminURLHelper):
    def get_action_url(self, action, *args, **kwargs): # -> str:
        ...
    


