default_install_hook_types: [pre-commit]
repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Format Python files with Ruff
        types: [python]
        stages: [pre-commit, manual]
        language: system
        require_serial: true
        entry: ruff format --force-exclude

      - id: run-ruff
        name: Run Ruff
        types: [python]
        stages: [pre-commit, manual]
        language: system
        require_serial: true
        entry: ruff check --force-exclude --output-format concise
