from django.utils.functional import cached_property as cached_property
from django.views.generic.base import ContextMixin, View
from wagtail import hooks as hooks
from wagtail.admin.admin_url_finder import AdminURLFinder as AdminURLFinder
from wagtail.admin.forms.choosers import (
    BaseFilterForm as BaseFilterForm,
    CollectionFilterMixin as CollectionFilterMixin,
    LocaleFilterMixin as LocaleFilterMixin,
    SearchFilterMixin as SearchFilterMixin,
)
from wagtail.admin.modal_workflow import render_modal_workflow as render_modal_workflow
from wagtail.admin.paginator import WagtailPaginator as WagtailPaginator
from wagtail.admin.ui.tables import Column as Column, LocaleColumn as LocaleColumn, Table as Table, TitleColumn as TitleColumn
from wagtail.coreutils import resolve_model_string as resolve_model_string
from wagtail.models import CollectionMember as CollectionMember, TranslatableMixin as TranslatableMixin
from wagtail.permission_policies import (
    BlanketPermissionPolicy as BlanketPermissionPolicy,
    ModelPermissionPolicy as ModelPermissionPolicy,
)
from wagtail.search.index import class_is_indexed as class_is_indexed

from _typeshed import Incomplete

class ModalPageFurnitureMixin(ContextMixin):
    icon: Incomplete
    page_title: Incomplete
    page_subtitle: Incomplete
    def get_context_data(self, **kwargs): ...

class ModelLookupMixin:
    model: Incomplete
    @cached_property
    def model_class(self): ...

class PreserveURLParametersMixin:
    preserve_url_parameters: Incomplete
    def append_preserved_url_parameters(self, url): ...

class CheckboxSelectColumn(Column):
    cell_template_name: str

class BaseChooseView(ModalPageFurnitureMixin, ModelLookupMixin, PreserveURLParametersMixin, ContextMixin, View):
    per_page: int
    ordering: Incomplete
    chosen_url_name: Incomplete
    chosen_multiple_url_name: Incomplete
    results_url_name: Incomplete
    icon: str
    page_title: Incomplete
    filter_form_class: Incomplete
    template_name: str
    results_template_name: str
    construct_queryset_hook_name: Incomplete
    url_filter_parameters: Incomplete
    paginator_class = WagtailPaginator
    @cached_property
    def i18n_enabled(self) -> bool: ...
    def get_object_list(self): ...
    def apply_object_list_ordering(self, objects): ...
    def get_filter_form_class(self): ...
    def get_filter_form(self): ...
    def filter_object_list(self, objects): ...
    def get_results_url(self): ...
    def get_chosen_multiple_url(self): ...
    @cached_property
    def is_multiple_choice(self): ...
    @property
    def columns(self) -> list[Column]: ...
    @property
    def title_column(self): ...
    @property
    def checkbox_column(self): ...
    paginator: Incomplete
    def get_results_page(self, request): ...
    filter_form: Incomplete
    results: Incomplete
    table: Incomplete
    def get(self, request): ...
    def get_context_data(self, **kwargs): ...
    def render_to_response(self) -> None: ...

class CreationFormMixin(ModelLookupMixin, PreserveURLParametersMixin):
    creation_form_class: Incomplete
    form_fields: Incomplete
    exclude_form_fields: Incomplete
    creation_form_template_name: str
    creation_tab_id: str
    create_action_label: Incomplete
    create_action_clicked_label: Incomplete
    create_url_name: Incomplete
    permission_policy: Incomplete
    def get_permission_policy(self): ...
    def can_create(self): ...
    def get_creation_form_class(self): ...
    def get_creation_form_kwargs(self): ...
    def get_creation_form(self): ...
    def get_create_url(self): ...
    def get_creation_form_context_data(self, form): ...

class ChooseViewMixin:
    search_tab_label: Incomplete
    creation_tab_label: Incomplete
    def get_context_data(self, **kwargs): ...
    def get_response_json_data(self): ...
    def render_to_response(self): ...

class ChooseView(ChooseViewMixin, CreationFormMixin, BaseChooseView): ...

class ChooseResultsViewMixin:
    def render_to_response(self): ...

class ChooseResultsView(ChooseResultsViewMixin, CreationFormMixin, BaseChooseView): ...

class ChosenResponseMixin:
    response_data_title_key: str
    chosen_response_name: str
    def get_object_id(self, instance): ...
    def get_display_title(self, instance): ...
    def get_edit_item_url(self, instance): ...
    def get_chosen_response_data(self, item): ...
    def get_multiple_chosen_response(self, items): ...
    def get_chosen_response(self, item): ...

class ChosenViewMixin(ModelLookupMixin):
    def get_object(self, pk): ...
    def get(self, request, pk): ...

class ChosenView(ChosenViewMixin, ChosenResponseMixin, View): ...

class ChosenMultipleViewMixin(ModelLookupMixin):
    def get_objects(self, pks): ...
    def get(self, request): ...

class ChosenMultipleView(ChosenMultipleViewMixin, ChosenResponseMixin, View): ...

class CreateViewMixin:
    model: Incomplete
    def dispatch(self, request, *args, **kwargs): ...
    form: Incomplete
    def get(self, request): ...
    def save_form(self, form): ...
    def post(self, request): ...
    def get_reshow_creation_form_response(self): ...

class CreateView(CreateViewMixin, CreationFormMixin, ChosenResponseMixin, View): ...
