from django.views.generic import View
from wagtail.admin.panels import get_edit_handler as get_edit_handler
from wagtail.models import PreviewableMixin as PreviewableMixin, RevisionMixin as RevisionMixin
from wagtail.utils.decorators import xframe_options_sameorigin_override as xframe_options_sameorigin_override

from _typeshed import Incomplete

class PreviewOnEdit(View):
    model: Incomplete
    form_class: Incomplete
    http_method_names: Incomplete
    preview_expiration_timeout: Incomplete
    session_key_prefix: str
    object: Incomplete
    def setup(self, request, *args, **kwargs) -> None: ...
    def dispatch(self, request, *args, **kwargs): ...
    def remove_old_preview_data(self) -> None: ...
    @property
    def session_key(self): ...
    def get_object(self): ...
    def get_form_class(self): ...
    def get_form(self, query_dict): ...
    def post(self, request, *args, **kwargs): ...
    def error_response(self): ...
    def get(self, request, *args, **kwargs): ...
    def delete(self, request, *args, **kwargs): ...

class PreviewOnCreate(PreviewOnEdit):
    @property
    def session_key(self): ...
    def get_object(self): ...

class PreviewRevision(View):
    model: Incomplete
    http_method_names: Incomplete
    pk: Incomplete
    revision_id: Incomplete
    object: Incomplete
    revision_object: Incomplete
    def setup(self, request, pk, revision_id, *args, **kwargs) -> None: ...
    def get_object(self): ...
    def get_revision_object(self): ...
    def get(self, request, *args, **kwargs): ...
