from _typeshed import Incomplete
from django.utils.functional import cached_property as cached_property
from wagtail.admin.admin_url_finder import AdminURLFinder as AdminURLFinder
from wagtail.admin.ui import tables as tables
from wagtail.admin.utils import get_latest_str as get_latest_str
from wagtail.admin.widgets.button import HeaderButton as HeaderButton
from wagtail.models import DraftStateMixin as DraftStateMixin, ReferenceIndex as ReferenceIndex

from .base import BaseListingView as BaseListingView, BaseObjectMixin as BaseObjectMixin
from .permissions import PermissionCheckedMixin as PermissionCheckedMixin

class TitleColumn(tables.TitleColumn):
    def get_link_attrs(self, instance, parent_context): ...

class UsageView(PermissionCheckedMixin, BaseObjectMixin, BaseListingView):
    paginate_by: int
    page_title: Incomplete
    index_url_name: Incomplete
    edit_url_name: Incomplete
    usage_url_name: Incomplete
    permission_required: str
    @cached_property
    def describe_on_delete(self): ...
    def get_object(self): ...
    def get_edit_url(self, instance): ...
    def get_usage_url(self, instance): ...
    def get_index_url(self): ...
    def get_page_subtitle(self): ...
    def get_breadcrumbs_items(self): ...
    @cached_property
    def header_buttons(self): ...
    def get_queryset(self): ...
    @cached_property
    def columns(self): ...
    def get_table(self, object_list, **kwargs): ...
    def get_context_data(self, *args, object_list: Incomplete | None = None, **kwargs): ...
