"""
This type stub file was generated by pyright.
"""

from typing import Any

from django_stubs_ext import StrOrPromise

from .base import Panel

class HelpPanel(Panel):
    """
    A panel to display helpful information to the user.

    This panel does not support the ``help_text`` parameter.
    """
    def __init__(self, content: StrOrPromise = ..., template: str = ..., **kwargs) -> None: ...

    def clone_kwargs(self): ...

    @property
    def clean_name(self) -> str: ...

    class BoundPanel(Panel.BoundPanel[HelpPanel, Any, Any]): ...
