"""
This type stub file was generated by pyright.
"""

from django.utils.functional import cached_property
from wagtail.telepath import Adapter

"""
Register Telepath adapters for core Django form widgets, so that they can
have corresponding Javascript objects with the ability to render new instances
and extract field values.
"""
class WidgetAdapter(Adapter):
    js_constructor: str
    def js_args(self, widget): # -> list[Any]:
        ...

    def get_media(self, widget):
        ...

    @cached_property
    def media(self): # -> Media:
        ...



class CheckboxInputAdapter(WidgetAdapter):
    js_constructor: str


class RadioSelectAdapter(WidgetAdapter):
    js_constructor: str


class SelectAdapter(WidgetAdapter):
    js_constructor: str


class ValidationErrorAdapter(Adapter):
    js_constructor: str
    def js_args(self, error): # -> list[Any]:
        ...

    @cached_property
    def media(self): # -> Media:
        ...



