"""
This type stub file was generated by pyright.
"""

class RemovedInWagtail70Warning(DeprecationWarning):
    ...


removed_in_next_version_warning = RemovedInWagtail70Warning
class RemovedInWagtail80Warning(PendingDeprecationWarning):
    ...


class MovedDefinitionHandler:
    """
    A wrapper for module objects to enable definitions to be moved to a new module, with a
    deprecation path for the old location. Importing the name from the old location will
    raise a deprecation warning (but will still complete successfully).

    To use, place the following code in the old module:

    import sys
    from wagtail.utils.deprecation import MovedDefinitionHandler, RemovedInWagtailXWarning

    MOVED_DEFINITIONS = {
        'SomeClassOrVariableName': 'path.to.new.module',
    }

    sys.modules[__name__] = MovedDefinitionHandler(sys.modules[__name__], MOVED_DEFINITIONS, RemovedInWagtailXWarning)

    If the name of the definition has also changed, you can specify its new name along with
    the path to its new module using a tuple. For example:

    MOVED_DEFINITIONS = {
        'SomeClassOrVariableName': ('path.to.new.module', 'NewClassOrVariableName'),
    }
    """
    def __init__(self, real_module, moved_definitions, warning_class) -> None:
        ...
    
    def __getattr__(self, name): # -> Any:
        ...
    


