"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class ObjectTypeRegistry:
    """
    Implements a lookup table for mapping objects to values according to the object type.
    The most specific type according to the object's inheritance chain is selected.
    """
    def __init__(self) -> None:
        ...

    def register(self, cls, value=..., exact_class=...):
        ...

    def get_by_type(self, cls):
        ...

    def get(self, obj):
        ...


class ModelFieldRegistry(ObjectTypeRegistry):
    """
    Handles the recurring pattern where we need to register different values for different
    model field types, and retrieve the one that most closely matches a given model field,
    according to its type (taking inheritance into account), and in the case of foreign keys,
    the type of the related model (again, taking inheritance into account).

    For example, this is used by wagtail.admin.forms.models when constructing model forms:
    we use such a registry to retrieve the appropriate dict of arguments to pass to the
    form field constructor. A lookup for a models.TextField will return a dict specifying a
    text area widget, and a lookup for a foreign key to Image will return a dict specifying
    an image chooser widget.
    """
    def __init__(self) -> None:
        ...

    def register(self, field_class, to=..., value=..., exact_class=...): ...  # type: ignore[override]

    def foreign_key_lookup(self, field):
        ...

