"""
This type stub file was generated by pyright.
"""

def get_version(version): # -> str:
    """Return a PEP 440-compliant version number from VERSION."""
    ...

def get_main_version(version=..., include_patch=...): # -> str:
    """Return main version (X.Y[.Z]) from VERSION."""
    ...

def get_complete_version(version=...): # -> tuple[int, int, int, str, int]:
    """
    Return a tuple of the Wagtail version. If version argument is non-empty,
    check for correctness of the tuple provided.
    """
    ...

def get_semver_version(version): # -> str:
    "Returns the semver version (X.Y.Z[-(alpha|beta)]) from VERSION"
    ...

