from collections import UserDict
from functools import cached_property

from _typeshed import Incomplete
from celery.utils.collections import AttributeDictMixin

from .utils import AppPickler

__all__ = ['Celery']

class PendingConfiguration(UserDict, AttributeDictMixin):
    callback: Incomplete
    def __init__(self, conf, callback) -> None: ...
    def __setitem__(self, key, value) -> None: ...
    def clear(self) -> None: ...
    def update(self, *args, **kwargs) -> None: ...
    def setdefault(self, *args, **kwargs): ...
    def __contains__(self, key) -> bool: ...
    def __len__(self) -> int: ...

class Celery:
    Pickler = AppPickler
    SYSTEM: Incomplete
    IS_macOS: Incomplete
    IS_WINDOWS: Incomplete
    main: Incomplete
    user_options: Incomplete
    steps: Incomplete
    amqp_cls: str
    backend_cls: Incomplete
    events_cls: str
    loader_cls: Incomplete
    log_cls: str
    control_cls: str
    task_cls: str
    registry_cls: str
    on_configure: Incomplete
    on_after_configure: Incomplete
    on_after_finalize: Incomplete
    on_after_fork: Incomplete
    clock: Incomplete
    set_as_current: Incomplete
    autofinalize: Incomplete
    namespace: Incomplete
    strict_typing: Incomplete
    configured: bool
    finalized: bool
    fixups: Incomplete
    use_fast_trace_task: bool
    def __init__(
        self,
        main=None,
        loader=None,
        backend=None,
        amqp=None,
        events=None,
        log=None,
        control=None,
        set_as_current: bool = True,
        tasks=None,
        broker=None,
        include=None,
        changes=None,
        config_source=None,
        fixups=None,
        task_cls=None,
        autofinalize: bool = True,
        namespace=None,
        strict_typing: bool = True,
        **kwargs,
    ) -> None: ...
    def on_init(self) -> None: ...
    def set_current(self) -> None: ...
    def set_default(self) -> None: ...
    def close(self) -> None: ...
    def start(self, argv=None): ...
    def worker_main(self, argv=None) -> None: ...
    def task(self, *args, **opts): ...
    def type_checker(self, fun, bound: bool = False): ...
    def register_task(self, task, **options): ...
    def gen_task_name(self, name, module): ...
    def finalize(self, auto: bool = False) -> None: ...
    def add_defaults(self, fun): ...
    def config_from_object(self, obj, silent: bool = False, force: bool = False, namespace=None): ...
    def config_from_envvar(self, variable_name, silent: bool = False, force: bool = False): ...
    def config_from_cmdline(self, argv, namespace: str = 'celery') -> None: ...
    def setup_security(
        self, allowed_serializers=None, key=None, key_password=None, cert=None, store=None, digest=..., serializer: str = 'json'
    ): ...
    def autodiscover_tasks(self, packages=None, related_name: str = 'tasks', force: bool = False): ...
    def send_task(
        self,
        name,
        args=None,
        kwargs=None,
        countdown=None,
        eta=None,
        task_id=None,
        producer=None,
        connection=None,
        router=None,
        result_cls=None,
        expires=None,
        publisher=None,
        link=None,
        link_error=None,
        add_to_parent: bool = True,
        group_id=None,
        group_index=None,
        retries: int = 0,
        chord=None,
        reply_to=None,
        time_limit=None,
        soft_time_limit=None,
        root_id=None,
        parent_id=None,
        route_name=None,
        shadow=None,
        chain=None,
        task_type=None,
        replaced_task_nesting: int = 0,
        **options,
    ): ...
    def connection_for_read(self, url=None, **kwargs): ...
    def connection_for_write(self, url=None, **kwargs): ...
    def connection(
        self,
        hostname=None,
        userid=None,
        password=None,
        virtual_host=None,
        port=None,
        ssl=None,
        connect_timeout=None,
        transport=None,
        transport_options=None,
        heartbeat=None,
        login_method=None,
        failover_strategy=None,
        **kwargs,
    ): ...
    broker_connection = connection
    def connection_or_acquire(self, connection=None, pool: bool = True, *_, **__): ...
    default_connection = connection_or_acquire
    def producer_or_acquire(self, producer=None): ...
    default_producer = producer_or_acquire
    def prepare_config(self, c): ...
    def now(self): ...
    def select_queues(self, queues=None): ...
    def either(self, default_key, *defaults): ...
    def bugreport(self): ...
    def signature(self, *args, **kwargs): ...
    def add_periodic_task(self, schedule, sig, args=(), kwargs=(), name=None, **opts): ...
    def create_task_cls(self): ...
    def subclass_with_self(self, Class, name=None, attribute: str = 'app', reverse=None, keep_reduce: bool = False, **kw): ...
    def __enter__(self): ...
    def __exit__(self, *exc_info) -> None: ...
    def __reduce__(self): ...
    def __reduce_v1__(self): ...
    def __reduce_keys__(self): ...
    def __reduce_args__(self): ...
    @cached_property
    def Worker(self): ...
    @cached_property
    def WorkController(self, **kwargs): ...
    @cached_property
    def Beat(self, **kwargs): ...
    @cached_property
    def Task(self): ...
    @cached_property
    def annotations(self): ...
    @cached_property
    def AsyncResult(self): ...
    @cached_property
    def ResultSet(self): ...
    @cached_property
    def GroupResult(self): ...
    @property
    def pool(self): ...
    @property
    def current_task(self): ...
    @property
    def current_worker_task(self): ...
    @cached_property
    def oid(self): ...
    @property
    def thread_oid(self): ...
    @cached_property
    def amqp(self): ...
    @property
    def backend(self): ...
    @property
    def conf(self): ...
    @conf.setter
    def conf(self, d) -> None: ...
    @cached_property
    def control(self): ...
    @cached_property
    def events(self): ...
    @cached_property
    def loader(self): ...
    @cached_property
    def log(self): ...
    @cached_property
    def tasks(self): ...
    @property
    def producer_pool(self): ...
    def uses_utc_timezone(self): ...
    @cached_property
    def timezone(self): ...

App = Celery
