from typing import NamedTuple

from _typeshed import Incomplete
from celery.utils.collections import ConfigurationView

__all__ = ['Settings', 'appstr', 'bugreport', 'filter_hidden_settings', 'find_app']

def appstr(app): ...

class Settings(ConfigurationView):
    deprecated_settings: Incomplete
    def __init__(self, *args, deprecated_settings=None, **kwargs) -> None: ...
    @property
    def broker_read_url(self): ...
    @property
    def broker_write_url(self): ...
    @property
    def broker_url(self): ...
    @property
    def result_backend(self): ...
    @property
    def task_default_exchange(self): ...
    @property
    def task_default_routing_key(self): ...
    @property
    def timezone(self): ...
    def without_defaults(self): ...
    def value_set_for(self, key): ...
    def find_option(self, name, namespace: str = ''): ...
    def find_value_for_key(self, name, namespace: str = 'celery'): ...
    def get_by_parts(self, *parts): ...
    def finalize(self): ...
    def table(self, with_defaults: bool = False, censored: bool = True): ...
    def humanize(self, with_defaults: bool = False, censored: bool = True): ...
    def maybe_warn_deprecated_settings(self): ...

class _settings_info_t(NamedTuple):  # noqa: N801 type stubs
    defaults: Incomplete
    convert: Incomplete
    key_t: Incomplete
    mix_error: Incomplete

class AppPickler:
    def __call__(self, cls, *args): ...
    def prepare(self, app, **kwargs) -> None: ...
    def build_kwargs(self, *args): ...  # noqa: ANN202 type stubs
    def build_standard_kwargs(  # noqa: ANN202 type stubs
        self, main, changes, loader, backend, amqp, events, log, control, accept_magic_kwargs, config_source=None
    ): ...
    def construct(self, cls, **kwargs): ...  # noqa: ANN202 type stubs

def filter_hidden_settings(conf): ...
def bugreport(app): ...
def find_app(app, symbol_by_name=..., imp=...): ...
