"""
This type stub file was generated by pyright.
"""

from typing import Any, Protocol

from django.forms.widgets import Media
from django.template import Context
from django.utils.safestring import SafeString

type RenderContext = Context | dict[str, Any]

class HasRenderHtmlMethod(Protocol):
    def render_html(self, parent_context: RenderContext | None) -> SafeString:
        ...


class HasRenderMethod(Protocol):
    def render(self) -> SafeString:
        ...

type Renderable = HasRenderHtmlMethod | HasRenderMethod

class HasMediaProperty(Protocol):
    @property
    def media(self) -> Media:
        ...
