"""
This type stub file was generated by pyright.
"""

from django import forms

class BooleanRadioSelect(forms.RadioSelect):
    """
    A radio select widget for boolean fields. Displays as three options; "All", "Yes" and "No".
    """

    input_type: str
    def __init__(self, attrs=...) -> None: ...
    def format_value(self, value):  # -> list[str] | Literal['']:
        ...
    def value_from_datadict(self, data, files, name):  # -> bool | None:
        ...
