"""
This type stub file was generated by pyright.
"""

from django import forms

class FilteredSelect(forms.Select):
    """
    A select box where the options are shown and hidden dynamically in response to another
    form field whose HTML `id` is specified in `filter_field`.

    The `choices` list accepts entries of the form `(value, label, filter_values)` in addition
    to the standard `(value, label)` tuples, where `filter_values` is a list of values;
    whenever `filter_field` is set to a non-empty value, only the items with that value in their
    `filter_values` list are shown.

    filter_field and filter_values are inserted as 'data-' attributes on the rendered HTML, where
    they are picked up by the JavaScript behaviour code -
    see wagtailadmin/js/filtered-select.js for an example of how these attributes are configured.
    """
    def __init__(self, attrs=..., choices=..., filter_field=...) -> None:
        ...
    
    def build_attrs(self, base_attrs, extra_attrs=...): # -> dict[str, Any]:
        ...
    
    def optgroups(self, name, value, attrs=...): # -> list[Any]:
        ...
    
    def create_option(self, name, value, label, selected, index, subindex=..., attrs=..., filter_value=...): # -> dict[str, Any]:
        ...
    
    @property
    def media(self): # -> Media:
        ...
    


