"""
This type stub file was generated by pyright.
"""

from django.forms import widgets

class SlugInput(widgets.TextInput):
    """
    Associates the input field with the Stimulus w-slug (SlugController).
    Slugifies content based on `WAGTAIL_ALLOW_UNICODE_SLUGS` and supports
    fields syncing their value to this field (see `TitleFieldPanel`) if
    also used.
    """
    def __init__(self, attrs=...) -> None:
        ...
    


