"""
This type stub file was generated by pyright.
"""

from taggit.forms import TagWidget

class AdminTagWidget(TagWidget):
    template_name = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def get_context(self, name, value, attrs): # -> dict[str, Any]:
        ...
    


