"""
This type stub file was generated by pyright.
"""

class Registry:
    def __init__(self) -> None:
        ...
    
    def register(self, cls): # -> None:
        ...
    
    def get_type_for_model(self, model): # -> None:
        ...
    
    def register_converted_field(self, field, converted): # -> None:
        ...
    
    def get_converted_field(self, field): # -> None:
        ...
    


registry = ...
def get_global_registry(): # -> Registry:
    ...

def reset_global_registry(): # -> None:
    ...

