"""
This type stub file was generated by pyright.
"""

from taggit.forms import TagField as TaggitTagField
from wagtail.admin.widgets import AdminTagWidget

def validate_tag_length(value, max_tag_length=...): # -> None:
    ...

class TagField(TaggitTagField):
    """
    Extends taggit's TagField with the option to prevent creating tags that do not already exist
    """
    widget = AdminTagWidget
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def clean(self, value): # -> list[Any] | Any:
        ...
    


