"""
This type stub file was generated by pyright.
"""

import re
from functools import lru_cache
from html import unescape
from django.core.validators import MaxLengthValidator
from django.db.models import Model
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.utils.safestring import mark_safe
from wagtail.rich_text.feature_registry import FeatureRegistry
from wagtail.rich_text.rewriters import EmbedRewriter, LinkRewriter, MultiRuleRewriter

features = ...
@lru_cache(maxsize=None)
def get_rewriter(): # -> MultiRuleRewriter:
    ...

def expand_db_html(html):
    """
    Expand database-representation HTML into proper HTML usable on front-end templates
    """
    ...

def extract_references_from_rich_text(html): # -> Generator[Any, Any, None]:
    ...

def get_text_for_indexing(richtext): # -> str:
    """
    Return a plain text version of a rich text string, suitable for search indexing;
    like Django's strip_tags, but ensures that whitespace is left between block elements
    so that <p>hello</p><p>world</p> gives "hello world", not "helloworld".
    """
    ...

class RichText:
    """
    A custom object used to represent a renderable rich text value.
    Provides a 'source' property to access the original source code,
    and renders to the front-end HTML rendering.
    Used as the native value of a wagtailcore.blocks.field_block.RichTextBlock.
    """
    def __init__(self, source) -> None:
        ...
    
    def __html__(self): # -> SafeString:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __bool__(self): # -> bool:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    


class EntityHandler:
    """
    An 'entity' is a placeholder tag within the saved rich text, which needs to be rewritten
    into real HTML at the point of rendering. Typically (but not necessarily) the entity will
    be a reference to a model to be fetched to have its data output into the rich text content
    (so that we aren't storing potentially changeable data within the saved rich text).

    An EntityHandler defines how this rewriting is performed.

    Currently Wagtail supports two kinds of entity: links (represented as <a linktype="...">...</a>)
    and embeds (represented as <embed embedtype="..." />).
    """
    @staticmethod
    def get_model():
        """
        If supported, returns the type of model able to be handled by this handler, e.g. Page.
        """
        ...
    
    @classmethod
    def get_instance(cls, attrs: dict) -> Model:
        ...
    
    @classmethod
    def get_many(cls, attrs_list: list[dict]) -> list[Model]:
        ...
    
    @staticmethod
    def expand_db_attributes(attrs: dict) -> str:
        """
        Given a dict of attributes from the entity tag
        stored in the database, returns the real HTML representation.
        """
        ...
    
    @classmethod
    def expand_db_attributes_many(cls, attrs_list: list[dict]) -> list[str]:
        """
        Given a list of attribute dicts from a list of entity tags stored in
        the database, return the real HTML representation of each one.
        """
        ...
    
    @classmethod
    def extract_references(cls, attrs): # -> list[Any]:
        """
        Yields a sequence of (content_type_id, object_id, model_path, content_path) tuples for the
        database objects referenced by this entity, as per
        wagtail.models.ReferenceIndex._extract_references_from_object
        """
        ...
    


class LinkHandler(EntityHandler):
    ...


class EmbedHandler(EntityHandler):
    ...


class RichTextMaxLengthValidator(MaxLengthValidator):
    """
    A variant of MaxLengthValidator that only counts text (not HTML tags) towards the limit
    Un-escapes entities for consistency with client-side character count.
    """
    def clean(self, x): # -> int:
        ...
    


