"""
This type stub file was generated by pyright.
"""

class FeatureRegistry:
    """
    A central store of information about optional features that can be enabled in rich text
    editors by passing a ``features`` list to the RichTextField, such as how to
    whitelist / convert HTML tags, and how to enable the feature on various editors.

    This information may come from diverse sources - for example, wagtailimages might define
    an 'images' feature and a Draftail plugin for it, while a third-party module might
    define a TinyMCE plugin for the same feature. The information is therefore collected into
    this registry via the 'register_rich_text_features' hook.
    """
    def __init__(self) -> None:
        ...
    
    def get_default_features(self): # -> list[Any]:
        ...
    
    def register_editor_plugin(self, editor_name, feature_name, plugin): # -> None:
        ...
    
    def get_editor_plugin(self, editor_name, feature_name): # -> None:
        ...
    
    def register_link_type(self, handler): # -> None:
        ...
    
    def get_link_types(self): # -> dict[Any, Any]:
        ...
    
    def register_embed_type(self, handler): # -> None:
        ...
    
    def get_embed_types(self): # -> dict[Any, Any]:
        ...
    
    def register_converter_rule(self, converter_name, feature_name, rule): # -> None:
        ...
    
    def get_converter_rule(self, converter_name, feature_name): # -> None:
        ...
    
    @staticmethod
    def function_as_entity_handler(identifier, fn): # -> type[EntityHandlerRegisteredAsFunction]:
        """Supports legacy registering of entity handlers as functions."""
        ...
    


