"""
This type stub file was generated by pyright.
"""

from django.db.models import Model
from django.http import HttpRequest
from wagtail.admin.menu import MenuItem, SubmenuMenuItem

from wagtail_modeladmin.options import ModelAdmin

class ModelAdminMenuItem[M: Model](MenuItem):
    """
    A sub-class of wagtail's MenuItem, used by PageModelAdmin to add a link
    to its listing page
    """
    model_admin: ModelAdmin[M]
    def __init__(self, model_admin: ModelAdmin[M], order: int) -> None:
        ...

    def is_shown(self, request: HttpRequest):
        ...



class GroupMenuItem(SubmenuMenuItem):
    """
    A sub-class of wagtail's SubmenuMenuItem, used by ModelAdminGroup to add a
    link to the admin menu with its own submenu, linking to various listing
    pages
    """
    def __init__(self, modeladmingroup, order, menu) -> None:
        ...
