"""
This type stub file was generated by pyright.
"""

from wagtail.admin.menu import MenuItem, SubmenuMenuItem

class ModelAdminMenuItem(MenuItem):
    """
    A sub-class of wagtail's MenuItem, used by PageModelAdmin to add a link
    to its listing page
    """
    def __init__(self, model_admin, order) -> None:
        ...

    def is_shown(self, request):
        ...



class GroupMenuItem(SubmenuMenuItem):
    """
    A sub-class of wagtail's SubmenuMenuItem, used by ModelAdminGroup to add a
    link to the admin menu with its own submenu, linking to various listing
    pages
    """
    def __init__(self, modeladmingroup, order, menu) -> None:
        ...
