"""
This type stub file was generated by pyright.
"""

def to_datetimepicker_format(python_format_string):
    """
    Given a python datetime format string, attempts to convert it to
    the nearest PHP datetime format string possible.
    """
    ...

